#!/usr/bin/env bash

# Hook to verify that merge commits are not made to the main branch accidentally
# Based on https://gist.github.com/ilyakatz/4625224#file-pre-commit-master-no-no

if [[ `git symbolic-ref HEAD` == "refs/heads/main" ]]
then
  echo "*************************"
  echo "You should not be merging to the main branch."
  echo
  echo "Your merges to main should be happening in a pull request on GitHub."
  echo "*************************"
  exit 1
fi