#!/usr/bin/env bash

# Hook to verify that commits are not made to the main branch accidentally
# Based on https://gist.github.com/ilyakatz/4625224#file-pre-commit-master-no-no

# Disallow all rebasing
echo "*************************"
echo "You should not be rebasing in this kit."
echo "*************************"
exit 1