#!/bin/bash 

# Hook to verify that commits are not made to the main branch accidentally
# Based on https://gist.github.com/ilyakatz/4625224#file-pre-commit-master-no-no

if [[ `git symbolic-ref HEAD` == "refs/heads/main" ]]
then
  echo "*************************"
  echo "You should not be committing to the main branch."
  echo
  echo "You should be committing to a feature branch."
  echo "You can create a branch with git checkout -b branchname"
  echo "*************************"
  exit 1
fi