#!/usr/bin/env bash

# Hook to verify that commits are not made to the main branch accidentally
# Based on https://gist.github.com/ilyakatz/4625224#file-pre-commit-master-no-no

if [[ `git symbolic-ref HEAD` == "refs/heads/main" ]]
then
  echo "*************************"
  echo "You should not be committing or merging to the main branch."
  echo
  echo "If you were trying to commit:"
  echo "    You should be committing to a feature branch."
  echo "    You can create a branch with 'git checkout -b branchname'"
  echo "If you were trying to merge:"
  echo "    You should be only be merging in a GitHub pull request."
  echo "*************************"
  git reset --merge
  exit 1
fi