#!/usr/bin/env bash

# Hook to verify that commits are not made to the main branch accidentally
# Based on https://gist.github.com/ilyakatz/4625224#file-pre-commit-master-no-no

if [[ `git symbolic-ref HEAD` == "refs/heads/main" ]]
then
  echo "*************************"
  echo "You should not be merging to the main branch."
  echo
  echo "    You should be only be merging in a GitHub pull request."
  echo "    The working tree is still in a MERGING state. Run the command 'git reset --merge'"
  echo "*************************"
  exit 1
fi